services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_NAME=bikeshop
      - DB_USER=bikeshopuser
      - DB_PASSWORD=password123
      - DB_HOST=db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bikeshop
      - POSTGRES_USER=bikeshopuser
      - POSTGRES_PASSWORD=password123

volumes:
  postgres_data:
